---
# tasks file for roles/base

- import_tasks: ssh.yml
- import_tasks: thp.yml

- name: Bash history tuning
  copy:
    src: bash.bashrc
    dest: /etc/bash.bashrc

- name: Update the entire system
 apt:
   state: latest
   upgrade: yes
   autoremove: yes
   update_cache: yes

- name: Install platform-specified sysadmin tools (Debian-based systems)
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - atop
    - htop
    - tcpdump
    - apt-file
    - nload
    - strace
    - lsof
    - iotop
    - nano
    - vim
    - dnsutils
    - curl
    - wget
    - iftop
    - mutt
    - screen
    - rsync
    - tcpflow
    - zabbix-agent
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install platform-specified sysadmin tools (RHEL-based)
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - htop
    - tcpdump
    - nload
    - strace
    - lsof
    - iotop
    - nano
    - vim
    - dnsutils
    - curl
    - wget
    - iftop
    - mutt
    - fail2ban
    - screen
    - rsync
    - tcpflow
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"

- name: Update apt-file cache
  shell: apt-file update
  changed_when: false
  ignore_errors: true
  async: 30
  poll: 0



